spring.application.name=gestion_tienda

#Configuracion de MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/gestion_tienda
spring.datasource.username=campus2023
spring.datasource.password=campus2023

#Cofiguración de JPA/Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
